artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/raw_data
  source_url: https://drive.google.com/drive/folders/1bNRBY0G1ylOUsJEK5DirXKsBBZkNmmRP?usp=sharing

data_preparation:
  root_dir: artifacts/prepared_data
  weather_data_path: artifacts/raw_data/weather
  energy_data_path: artifacts/raw_data/energy
  training_data_path: artifacts/prepared_data/train
  test_data_path: artifacts/prepared_data/tests

training:
  root_dir: artifacts/training
  training_data_path: artifacts/prepared_data/model_data.parquet
  trained_models_path: artifacts/training/models

evaluation:
  path_to_models: artifacts/training/models
  training_data_path: artifacts/prepared_data/model_data.parquet
  mlflow_uri: https://dagshub.com/tombeihofer23/DoPro2.mlflow