name: daily-prediction

on:
  schedule:
    - cron: '*/1 * * * *' # Every day at 07:30
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: first-step
        run: echo "hello world"
